version: '3'

services:

  analyzer-wcec-api:
    container_name: analyzer-wcec-api
    image:  greenstamp/analyzer-wcec-api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4002:3000
    volumes:
      - /data/greenstamp/pipe:/hostpipe
      - /data/greenstamp/wcec:/test
      - /data/greenstamp/analyzer-wcec-api:/data
    environment:
      DELIVER_RESULTS_ENDPOINT: 'http://51.210.255.156:3000/api/result'
      UPLOADS_HOME: '/data'
